apiVersion: v1
kind: Service
metadata:
    name: sample-service
    labels:
      name: app-v1

spec: 
  ports:
  - port: 80
    nodePort: 30006
    protocol: TCP

  selector:
       app: app-v2
  type: LoadBalancer
