apiVersion: v1
kind: Service
metadata:
    name: sample-service
    labels:
      name: app-v1

spec: 
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP

  selector:
       app: app-v1
  type: LoadBalancer
