apiVersion: v1
kind: Service
metadata:
    name: sample-service2
    labels:
      name: app-v2

spec: 
  ports:
  - port: 80
    nodePort: 30007
    protocol: TCP

  selector:
       app: app-v2
  type: LoadBalancer
